### ISSUE TITLE
Disabled in Kodi 17

### ISSUE THREAD

**Issue by prof-ninjason** [davejm/plugin.video.lynda#8] opened 2017-04-05 22:55 UTC
This has been disabled in Kodi 17 due to being incompatible. Not sure what else you need.

**Comment by davejm** [comment] 2017-04-06 07:11
Thanks for the heads up. I'll aim to have this fixed by the end of this weekend. I hope to setup a repo as well so you don't need to manually update each time.

**Comment by DataBass504** [comment] 2017-04-18 06:59
I've just tried installing on Kodi 17.1 (LibreElec) on my rpi3 and it's giving me this message in my event logs:
"Failed to install Add-on from zip file
The dependency on xbmc.python version 3.0 could not be satisfied?"

Have you sorted out the issue yet & perhaps it's not compatible with the raspberry pi?  I'd love to have this working, thanks in advance.

**Comment by davejm** [comment] 2017-04-18 12:40
@DataBass504 thanks for the error log. I'm working on fixing this but there's been another change in the login flow that stopped me

**Comment by davejm** [comment] 2017-04-18 14:28
@jcrochon @DataBass504 hopefully the latest version on master should fix the disabled problem. However, login functionality still seems broken for organisational accounts. I'll be looking into this later.
Can either of you confirm this issue is fixed?

**Comment by prof-ninjason** [comment] 2017-04-18 14:38
I will test this after work 6PM CST. If it helps, I am using Kodibuntu 14.04 LTS with all upgrades, including Kodi 17.

**Comment by DataBass504** [comment] 2017-04-18 20:54
Thanks @davejm for the quick response, I just tried installing the new master zip & I'm now receiving an error stating it failed due to an invalid structure. Hope you're able to get everything in working condition, good luck.

**Comment by prof-ninjason** [comment] 2017-04-24 18:33
It Works! Thank you very much for all the help.

**Comment by davejm** [comment] 2017-04-26 21:40
@DataBass504 sorry to hear that. I can't reproduce. Not sure what's going on there.

**Comment by davejm** [comment] 2017-04-26 21:40
@jcrochon no problem! :smile:

**Comment by DataBass504** [comment] 2017-05-05 15:01
@davejm Just wanted to let you know I redownloaded the master zip & all is working well on RPi3 LibreElec 17.1, thanks!

**Closed as completed** 2017-05-05 15:11 UTC
Labels: bug
